title: Ben McDaniel # your name (or website title) here
logo: "/images/HEADSHOT.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Master of Science in Data Analytics
  <br><br>
  <a href="https://www.linkedin.com/in/ben-mcdaniel375">View My LinkedIn Profile</a> 
  <br><br>
  <div data-iframe-width="150" data-iframe-height="270" data-share-badge-id="531fe040-b690-4260-8fef-f69ac1a41eb7" data-share-badge-host="https://www.credly.com">
  </div>
  <script type="text/javascript" async src="//cdn.credly.com/assets/utilities/embed.js"></script>
  
theme: jekyll-theme-minimal
google_analytics:  G-WB03SR0FY7 # your Google Analytics tracking ID here
